version: '3.8'

services:
  # OCR Web应用服务
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ocr-web
    ports:
      - "5002:5000"  # 将容器的5000端口映射到主机的5002端口
    volumes:
      - ./uploads:/app/uploads  # 挂载上传目录，保证数据持久化
    environment:
      - SECRET_KEY=your-secret-key-here  # 应用密钥，生产环境中应使用强密码
      - MAX_CONTENT_LENGTH=52428800      # 50MB 最大上传文件大小
      - MAX_FILES=10                     # 最大同时处理文件数
      - CONCURRENT_PROCESSES=1           # OCR处理并发数
    deploy:
      resources:
        limits:
          cpus: '1'                      # 限制CPU使用
          memory: 1G                     # 限制内存使用
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s                      # 降低健康检查间隔，更快发现问题
      timeout: 5s
      retries: 3
    restart: unless-stopped              # 除非手动停止，否则总是重启容器
    logging:
      driver: "json-file"
      options:
        max-size: "10m"                  # 限制日志大小
        max-file: "3" 
